version: '3'
services:
  blue_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blue_app
    ports:
      - "8081:80"
    restart: always

  green_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: green_app
    ports:
      - "8082:80"
    restart: always
