version: '3'
services:
  green_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: green_app
    volumes:
      - ./app/green:/usr/share/nginx/html
    ports:
      - "8082:80"
    restart: always
