name: Deploy Without Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload files to Green EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.GREEN_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        source: "."
        target: "/home/ubuntu/bluegreen-app"

    - name: Deploy on Green EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.GREEN_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ubuntu/bluegreen-app
          docker-compose down || true
          docker-compose up -d --build

    - name: Health Check on Green
      run: |
        sleep 5
        curl --fail http://${{ secrets.GREEN_IP }}:8080 || exit 1

    - name: (Optional) Switch Nginx to Green
      if: success()
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.PROXY_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo sed -i 's/BLUE_IP/${{ secrets.GREEN_IP }}/g' /etc/nginx/nginx.conf
          sudo systemctl reload nginx
