    - name: Health Check on Green (via SSH)
      id: health
      continue-on-error: true
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.GREEN_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          curl --fail http://localhost:${{ env.GREEN_PORT }} || exit 1

    - name: Ensure Nginx is installed on Proxy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.PROXY_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo apt update
          sudo apt install -y nginx
          sudo systemctl enable nginx
          sudo systemctl start nginx

    - name: Rollback to Blue if health check fails
      if: steps.health.outcome == 'failure'
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.PROXY_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "❌ Health check failed. Switching Proxy to BLUE"
          sudo ln -sf /etc/nginx/sites-available/blue.conf /etc/nginx/sites-enabled/current
          sudo systemctl reload nginx

    - name: Switch traffic to Green if health check passes
      if: steps.health.outcome == 'success'
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.PROXY_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "✅ Green passed. Switching Proxy to GREEN"
          sudo ln -sf /etc/nginx/sites-available/green.conf /etc/nginx/sites-enabled/current
          sudo systemctl reload nginx
